server:
  port: 8888
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Kirvlstep2006/resources
          default-label: main
          search-paths: configs/*
          clone-on-start: true
          force-pull: true
          username: Kirvlstep2006
          password: Kirvl050906
